wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.22.2
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1760439358
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 71
      - 95
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 71
      - 95
      - 98
      - 105
      3:
      - 7
      - 42
      - 66
      4: 3.10.18
      5: 0.22.2
      6: 4.37.2
      9:
        1: transformers_trainer
      13: linux-x86_64
    e:
      8zf29ibx8ey4j4vfrr5lcz2gdve1tbd7:
        os: Linux-5.15.0-140-generic-x86_64-with-glibc2.35
        python: CPython 3.10.18
        started_at: '2025-10-14T10:55:57.826753Z'
        args:
        - --local_rank=0
        - --deepspeed
        - ./scripts/zero3.json
        - --model_name_or_path
        - /vast/users/xiaodan/haokunlin/Continual_LLaVA/llava/output/llava-v1.5-7b
        - --version
        - v1
        - --data_path
        - /vast/users/xiaodan/haokunlin/data/llava_med_for_cv805/upload_hf/training/CT_data_3995.json
        - --cl_data_clss
        - CT
        - --image_folder
        - /vast/users/xiaodan/haokunlin/data/llava_med_for_cv805/upload_hf/training_images/CT_data
        - --vision_tower
        - /vast/users/xiaodan/haokunlin/Continual_LLaVA/llava/output/clip-vit-large-patch14-336
        - --mm_projector_type
        - mlp2x_gelu
        - --mm_vision_select_layer
        - '-2'
        - --mm_use_im_start_end
        - 'False'
        - --mm_use_im_patch_token
        - 'False'
        - --image_aspect_ratio
        - pad
        - --group_by_modality_length
        - 'True'
        - --bf16
        - 'True'
        - --output_dir
        - ./output/llava-med_CT
        - --num_train_epochs
        - '1'
        - --per_device_train_batch_size
        - '4'
        - --per_device_eval_batch_size
        - '4'
        - --gradient_accumulation_steps
        - '1'
        - --evaluation_strategy
        - 'no'
        - --save_strategy
        - steps
        - --save_steps
        - '50000'
        - --save_total_limit
        - '1'
        - --learning_rate
        - 2e-5
        - --weight_decay
        - '0.'
        - --warmup_ratio
        - '0.03'
        - --lr_scheduler_type
        - cosine
        - --logging_steps
        - '1'
        - --tf32
        - 'False'
        - --model_max_length
        - '2048'
        - --gradient_checkpointing
        - 'True'
        - --dataloader_num_workers
        - '4'
        - --lazy_preprocess
        - 'True'
        - --disable_task_id
        - 'False'
        - --dataset_type
        - newdomain
        - --report_to
        - wandb
        - --retriever_state_dict
        - /vast/users/xiaodan/haokunlin/Continual_LLaVA/llava/output/prompt-key/merged_prompt_key.pth
        program: /vast/users/xiaodan/haokunlin/Continual_LLaVA/llava/train/train_mem.py
        code_path: llava/train/train_mem.py
        code_path_local: llava/train/train_mem.py
        git:
          remote_url: https://github.com/mengcaopku/Continual_LLaVA.git
          commit: aa344ffb35af786b8f27a5e99e4db6c87e824a61
        email: zhangjian.em@gmail.com
        root: /vast/users/xiaodan/haokunlin/Continual_LLaVA
        host: auh7-1b-gpu-222
        executable: /vast/users/xiaodan/miniconda3/envs/llava/bin/python3.10
        writer_id: 8zf29ibx8ey4j4vfrr5lcz2gdve1tbd7
    m:
    - 1: train/global_step
      6:
      - 3
vocab_size:
  desc: null
  value: 32000
max_position_embeddings:
  desc: null
  value: 4096
hidden_size:
  desc: null
  value: 4096
intermediate_size:
  desc: null
  value: 11008
num_hidden_layers:
  desc: null
  value: 32
num_attention_heads:
  desc: null
  value: 32
num_key_value_heads:
  desc: null
  value: 32
hidden_act:
  desc: null
  value: silu
initializer_range:
  desc: null
  value: 0.02
rms_norm_eps:
  desc: null
  value: 1.0e-05
pretraining_tp:
  desc: null
  value: 1
use_cache:
  desc: null
  value: false
rope_theta:
  desc: null
  value: 10000.0
rope_scaling:
  desc: null
  value: null
attention_bias:
  desc: null
  value: false
attention_dropout:
  desc: null
  value: 0.0
return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
output_attentions:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
torch_dtype:
  desc: null
  value: float16
use_bfloat16:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: false
chunk_size_feed_forward:
  desc: null
  value: 0
is_encoder_decoder:
  desc: null
  value: false
is_decoder:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
max_length:
  desc: null
  value: 4096
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
num_beams:
  desc: null
  value: 1
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
no_repeat_ngram_size:
  desc: null
  value: 0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
remove_invalid_values:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
architectures:
  desc: null
  value:
  - LlavaLlamaForCausalLM
finetuning_task:
  desc: null
  value: null
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: 1
pad_token_id:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: 2
sep_token_id:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
_name_or_path:
  desc: null
  value: /vast/users/xiaodan/haokunlin/Continual_LLaVA/llava/output/llava-v1.5-7b
transformers_version:
  desc: null
  value: 4.37.2
freeze_mm_mlp_adapter:
  desc: null
  value: false
freeze_mm_vision_resampler:
  desc: null
  value: false
image_aspect_ratio:
  desc: null
  value: pad
mm_hidden_size:
  desc: null
  value: 1024
mm_projector_type:
  desc: null
  value: mlp2x_gelu
mm_resampler_type:
  desc: null
  value: null
mm_use_im_patch_token:
  desc: null
  value: false
mm_use_im_start_end:
  desc: null
  value: false
mm_vision_select_feature:
  desc: null
  value: patch
mm_vision_select_layer:
  desc: null
  value: -2
mm_vision_tower:
  desc: null
  value: /vast/users/xiaodan/haokunlin/Continual_LLaVA/llava/output/clip-vit-large-patch14-336
model_type:
  desc: null
  value: llava_llama
tune_mm_mlp_adapter:
  desc: null
  value: false
tune_mm_vision_resampler:
  desc: null
  value: false
unfreeze_mm_vision_tower:
  desc: null
  value: false
use_mm_proj:
  desc: null
  value: true
model_name:
  desc: null
  value: /vast/users/xiaodan/haokunlin/Continual_LLaVA/llava/output/llava-v1.5-7b
dataset_type:
  desc: null
  value: newdomain
task:
  desc: null
  value: CT
preprare_retreival_version:
  desc: null
  value: firstq
retriever_state_dict:
  desc: null
  value: /vast/users/xiaodan/haokunlin/Continual_LLaVA/llava/output/prompt-key/merged_prompt_key.pth
disable_task_id:
  desc: null
  value: false
pool_size:
  desc: null
  value: 64
weight_topk:
  desc: null
  value: 4
random_dropout:
  desc: null
  value: null
low_rank:
  desc: null
  value: 8
groups:
  desc: null
  value: 4
similarity_type:
  desc: null
  value: cosine
pool_train_keys:
  desc: null
  value: true
pool_train_weights:
  desc: null
  value: true
dataset_type_map:
  desc: null
  value:
    domain:
      chartqa:
      - 0
      - 8
      docvqa:
      - 8
      - 16
      iconqa:
      - 16
      - 24
      medicalqa:
      - 24
      - 32
    newdomain:
      GeoChat_Instruct:
      - 0
      - 8
      llava_med:
      - 8
      - 16
      atom:
      - 16
      - 24
      art:
      - 24
      - 32
      astro:
      - 32
      - 40
      agri:
      - 40
      - 48
      chem:
      - 48
      - 56
      climate:
      - 56
      - 64
    dataset:
      ScienceQA:
      - 0
      - 8
      TextVQA:
      - 8
      - 16
      ImageNet:
      - 16
      - 24
      GQA:
      - 24
      - 32
      VizWiz:
      - 32
      - 40
      Grounding:
      - 40
      - 48
      VQAv2:
      - 48
      - 56
      OCRVQA:
      - 56
      - 64
    llava-med:
      CT:
      - 0
      - 8
      CXR:
      - 8
      - 16
      Histopathology:
      - 16
      - 24
      MRI:
      - 24
      - 32
task_pool_index_range:
  desc: null
  value:
    GeoChat_Instruct:
    - 0
    - 8
    llava_med:
    - 8
    - 16
    atom:
    - 16
    - 24
    art:
    - 24
    - 32
    astro:
    - 32
    - 40
    agri:
    - 40
    - 48
    chem:
    - 48
    - 56
    climate:
    - 56
    - 64
mm_patch_merge_type:
  desc: null
  value: flat
tokenizer_padding_side:
  desc: null
  value: right
tokenizer_model_max_length:
  desc: null
  value: 2048
mm_projector_lr:
  desc: null
  value: null
output_dir:
  desc: null
  value: ./output/llava-med_CT
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: false
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: 'no'
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 4
per_device_eval_batch_size:
  desc: null
  value: 4
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 2.0e-05
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 1.0
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: cosine
lr_scheduler_kwargs:
  desc: null
  value: {}
warmup_ratio:
  desc: null
  value: 0.03
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ./output/llava-med_CT/runs/Oct14_10-54-48_auh7-1b-gpu-222
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 1.0
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: steps
save_steps:
  desc: null
  value: 50000
save_total_limit:
  desc: null
  value: 1
save_safetensors:
  desc: null
  value: true
save_on_each_node:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: true
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 4
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: ./output/llava-med_CT
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: false
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
deepspeed:
  desc: null
  value: ./scripts/zero3.json
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: adamw_torch
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
dataloader_persistent_workers:
  desc: null
  value: false
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: false
hub_always_push:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: true
gradient_checkpointing_kwargs:
  desc: null
  value: null
include_inputs_for_metrics:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
dispatch_batches:
  desc: null
  value: null
split_batches:
  desc: null
  value: false
include_tokens_per_second:
  desc: null
  value: false
include_num_input_tokens_seen:
  desc: null
  value: false
neftune_noise_alpha:
  desc: null
  value: null
cache_dir:
  desc: null
  value: null
mpt_attn_impl:
  desc: null
  value: triton
model_max_length:
  desc: null
  value: 2048
double_quant:
  desc: null
  value: true
quant_type:
  desc: null
  value: nf4
bits:
  desc: null
  value: 16
lora_enable:
  desc: null
  value: false
lora_r:
  desc: null
  value: 64
lora_alpha:
  desc: null
  value: 16
lora_dropout:
  desc: null
  value: 0.05
lora_weight_path:
  desc: null
  value: ''
lora_bias:
  desc: null
  value: none
group_by_modality_length:
  desc: null
  value: true
